export const FETCH_CREATE_TASK_REQUEST = "FETCH_CREATE_TASK_REQUEST";
export const FETCH_CREATE_TASK_SUCCESS = "FETCH_CREATE_TASK_SUCCESS";
export const FETCH_CREATE_TASK_FAILURE = "FETCH_CREATE_TASK_FAILURE";